# Bukkit config file for LunaticChat
privateMessage:
  - '{"text":"{SENDER}", "color":"white"}'
  - '{"text":" to ", "color":"white"}'
  - '{"text":"{TARGET}", "color":"white"}'
  - '{"text":" >> ", "color":"gray"}'
  - '{"text":"{MESSAGE}", "color": "gray"}'
channelFormats:
  local:
    - '{"text":"%vault_prefix%%player_displayname%%vault_suffix%", "color":"white"}'
    - '{"text":" >> ", "color":"gray"}'
    - '{"text":"{MESSAGE}", "color":"gray"}'
  global:
    - '{"text":"[GLOBAL] ", "color":"yellow"}'
    - '{"text":"%vault_prefix%%player_displayname%%vault_suffix%", "color":"white"}'
    - '{"text":" >> ", "color":"gray"}'
    - '{"text":"{MESSAGE}", "color":"gray"}'
  staff:
    - '{"text":"[STAFF] ", "color":"green"}'
    - '{"text":"%vault_prefix%%player_displayname%%vault_suffix%", "color":"white"}'
    - '{"text":" >> ", "color":"gray"}'
    - '{"text":"{MESSAGE}", "color":"gray"}'