name: LunaticChat
version: ${project.version}
main: xyz.poulton.lunaticchat.spigot.LunaticChatSpigot
api-version: 1.15
authors: [__lucyy]
description: BungeeCord chat plugin, supporting raw JSON text components
depend: [PlaceholderAPI]
commands:
  channel:
    description: Set your chat channel
    usage: "Usage: /channel <channel>"
    aliases: [ch]
  reloadchat:
    description: Reloads chat
    usage: "Usage: /reloadchat"
    aliases: [rchat, rch]
  message:
    description: Sends a message to another player on the network
    usage: "Usage: /message <player> <message>"
    aliases: [msg,tell,t,whisper,w]
  reply:
    description: Replies to a message from another player on the network
    usage: "Usage: /reply <message>"
    aliases: [r]